### ISSUE TITLE
Path tracking problem

### ISSUE THREAD

**Issue by nixwang** [larics/nbvp_exploration#2]
From the vedio, this drone seems like tracked the whole best path instead of the first node of the best path like NBVP2016, is it true?
Can you share the path excute code or project, please?
Thank you

**Comment by AnaBatinovic** [comment]
Hi @nixwang, the idea of the algorithm is that a robot executes the whole path as described in the [paper](https://ieeexplore.ieee.org/document/9695290). The algorithm uses the [larics_motion_planning](https://github.com/larics/larics_motion_planning) repository for path planning.
Thank you!

**Comment by nixwang** [comment]
Okay, I got it. 
Thanks for your kindly reply.
